export const GET_CRYPTO = 'GET_CRYPTO';
export const COMPARE_CRYPTO = 'COMPARE_CRYPTO';
export const ON_SELECT = 'ON_SELECT';
export const SET_ONCHANGE_INPUT = 'SET_ONCHANGE_INPUT';
export const ON_SELECT_CONVERTER = 'ON_SELECT_CONVERTER';
export const SET_VALUE_NUMBER = 'SET_VALUE_NUMBER';
export const SET_TWO_COIN_NAME = 'SET_TWO_COIN_NAME';
